CinemaTicketOffice/CinemaTicketOffice.Web/Controllers/OrderController.cs
using CinemaTicketOffice.Domain.Models.Domain;
using CinemaTicketOffice.Service.Interface;
using GemBox.Document;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text;

namespace CinemaTicketOffice.Web.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
            ComponentInfo.SetLicense("FREE-LIMITED-KEY");
        }

        public IActionResult Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            List<Order> orders = _orderService.GetAllOrders().Where(x => x.UserId == userId).ToList();
            return View(orders);
        }

        public IActionResult CreateInvoice(Guid id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            Order order = _orderService.GetAllOrders().Where(x => x.UserId == userId && x.Id == id).SingleOrDefault();

            var templatePath = Path.Combine(Directory.GetCurrentDirectory(), "Templates\\InvoiceTemplate.docx");
            var document = DocumentModel.Load(templatePath);

            document.Content.Replace("{{OrderNumber}}", order.Id.ToString());
            document.Content.Replace("{{CustomerDetails}}", (order.User.FirstName + " " + order.User.LastName + " (" + order.User.Email + ")"));
            StringBuilder sb = new StringBuilder();
            foreach (var item in order.TicketInOrderCollection)
                sb.AppendLine("Ticket(s) for " + item.Ticket.MovieName + " with quantity of " + item.Quantity + " and price of $" + item.Ticket.Price + ". (Subtotal: $" + (item.Ticket.Price * item.Quantity) + ")");
            document.Content.Replace("{{Tickets}}", sb.ToString());
            document.Content.Replace("{{TotalPrice}}", "$" + order.TotalPrice().ToString());

            var stream = new MemoryStream();
            document.Save(stream, new PdfSaveOptions());
            return File(stream.ToArray(), new PdfSaveOptions().ContentType, "InvoiceOrder" + order.Id.ToString() + ".pdf");
        }
    }
}

CinemaTicketOffice/CinemaTicketOffice.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CinemaTicketOffice.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div id="page-wrapper">
        <header>
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cinema Ticket Office</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbar">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>@if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Users</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                                </li>
                            }
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="Index">Shopping Cart</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                                </li>
                            }
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
        </header>
        <main role="main">
            @RenderBody()
        </main>
        <footer class="footer bg-body-tertiary">
            <div class="container small py-3">
                &copy; 2023 - Cinema Ticket Office - Dimitar Peshevski, Faculty of Computer Science and Engineering
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/popper.js/umd/popper.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>